import os
import uuid
import logging
from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from sqlalchemy.orm import Session as DBSession
from database import get_db
from models import Session, DocOutput, File

# reportlab imports
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

# python-docx imports
from docx import Document

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/doc", tags=["export"])

# Base uploads path
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "uploads", "outputs")
os.makedirs(OUTPUT_DIR, exist_ok=True)

@router.get("/{session_id}/export/docx")
def export_docx(session_id: str, db: DBSession = Depends(get_db)):
    """
    Generates a structured Word Document (.docx) of the document analysis results.
    """
    try:
        session_uuid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session UUID")

    # Fetch session and output
    session = db.query(Session).filter(Session.id == session_uuid).first()
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    output = db.query(DocOutput).filter(DocOutput.session_id == session_uuid).first()
    if not output:
        raise HTTPException(status_code=404, detail="No document analysis results found for this session")

    # Define path
    filename = f"{session_uuid}_analysis.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)

    logger.info(f"Generating DOCX export at: {filepath}")

    # Build Word Document
    doc = Document()
    doc.add_heading(f"Doc Analysis: {session.input_label or 'Untitled Document'}", 0)

    doc.add_heading("Structured Summary", level=1)
    doc.add_paragraph(output.structured_summary or "No summary generated.")

    doc.add_heading("Product Description", level=1)
    doc.add_paragraph(output.product_description or "No product description generated.")

    doc.add_heading("Implementation Requirements", level=1)
    reqs = output.implementation_requirements or {}
    
    if reqs:
        for category, items in reqs.items():
            doc.add_heading(category.replace("_", " ").title(), level=2)
            if isinstance(items, list) and len(items) > 0:
                for item in items:
                    text = item if isinstance(item, str) else item.get("text", "")
                    priority = "" if isinstance(item, str) else item.get("priority", "")
                    priority_str = f" [{priority}]" if priority else ""
                    doc.add_paragraph(f"{text}{priority_str}", style="List Bullet")
            else:
                doc.add_paragraph("No requirements extracted for this category.", style="List Bullet")
    else:
        doc.add_paragraph("No requirements available.")

    if output.assumptions:
        doc.add_heading("Assumptions", level=1)
        if isinstance(output.assumptions, list):
            for item in output.assumptions:
                text = item if isinstance(item, str) else item.get("text", "")
                doc.add_paragraph(text, style="List Bullet")
        else:
            doc.add_paragraph(str(output.assumptions))

    if output.open_questions:
        doc.add_heading("Open Questions", level=1)
        if isinstance(output.open_questions, list):
            for item in output.open_questions:
                text = item if isinstance(item, str) else item.get("text", "")
                doc.add_paragraph(text, style="List Bullet")
        else:
            doc.add_paragraph(str(output.open_questions))

    doc.add_paragraph("")
    footer_para = doc.add_paragraph()
    footer_para.alignment = 1 # Centered
    run = footer_para.add_run("Generated by DocPPT Intelligence Tool")
    run.italic = True

    # Save
    doc.save(filepath)

    # Log to files table if not already exists
    existing_file = db.query(File).filter(
        File.session_id == session_uuid,
        File.file_role == "output",
        File.file_type == "docx"
    ).first()

    if not existing_file:
        db_file = File(
            session_id=session_uuid,
            user_id=session.user_id,
            file_role="output",
            file_type="docx",
            storage_path=filepath,
            original_filename=f"{session.input_label or 'document'}_analysis.docx",
            mime_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            size_bytes=os.path.getsize(filepath)
        )
        db.add(db_file)
        db.commit()

    return FileResponse(
        filepath,
        filename=f"{session.input_label or 'document'}_analysis.docx",
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )

@router.get("/{session_id}/export/pdf")
def export_pdf(session_id: str, db: DBSession = Depends(get_db)):
    """
    Generates a beautiful high-fidelity PDF report of the document analysis results using reportlab.
    """
    try:
        session_uuid = uuid.UUID(session_id)
    except ValueError:
        raise HTTPException(status_code=400, detail="Invalid session UUID")

    # Fetch session and output
    session = db.query(Session).filter(Session.id == session_uuid).first()
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    output = db.query(DocOutput).filter(DocOutput.session_id == session_uuid).first()
    if not output:
        raise HTTPException(status_code=404, detail="No document analysis results found for this session")

    # Define path
    filename = f"{session_uuid}_analysis.pdf"
    filepath = os.path.join(OUTPUT_DIR, filename)

    logger.info(f"Generating PDF export at: {filepath}")

    # Build reportlab document template
    doc_template = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=54, leftMargin=54,
        topMargin=54, bottomMargin=54
    )

    styles = getSampleStyleSheet()

    # Define styled palette
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=22,
        leading=26,
        textColor=colors.HexColor("#7c3aed"), # Accent purple
        spaceAfter=15
    )
    h1_style = ParagraphStyle(
        "CustomH1",
        parent=styles["Heading2"],
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#111827"), # Deep dark gray
        spaceBefore=14,
        spaceAfter=6,
        keepWithNext=True
    )
    h2_style = ParagraphStyle(
        "CustomH2",
        parent=styles["Heading3"],
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#4b5563"), # Cool gray
        spaceBefore=10,
        spaceAfter=4,
        keepWithNext=True
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#1f2937"), # Charcoal body
        spaceAfter=8
    )
    bullet_style = ParagraphStyle(
        "CustomBullet",
        parent=styles["Normal"],
        fontSize=9.5,
        leading=13.5,
        textColor=colors.HexColor("#1f2937"),
        leftIndent=15,
        firstLineIndent=-10,
        spaceAfter=4
    )
    footer_style = ParagraphStyle(
        "CustomFooter",
        parent=styles["Italic"],
        fontSize=8,
        leading=10,
        textColor=colors.HexColor("#9ca3af"),
        alignment=1
    )

    story = []

    # Title
    story.append(Paragraph(f"Document Intelligence Report: {session.input_label or 'Untitled Document'}", title_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#e5e7eb"), spaceAfter=15))

    # Structured Summary
    story.append(Paragraph("Structured Summary", h1_style))
    story.append(Paragraph(output.structured_summary or "No summary generated.", body_style))
    story.append(Spacer(1, 8))

    # Product Description
    story.append(Paragraph("Product Description", h1_style))
    story.append(Paragraph(output.product_description or "No product description generated.", body_style))
    story.append(Spacer(1, 8))

    # Requirements
    story.append(Paragraph("Implementation Requirements", h1_style))
    reqs = output.implementation_requirements or {}
    
    if reqs:
        for category, items in reqs.items():
            story.append(Paragraph(category.replace("_", " ").title(), h2_style))
            if isinstance(items, list) and len(items) > 0:
                for item in items:
                    text = item if isinstance(item, str) else item.get("text", "")
                    priority = "" if isinstance(item, str) else item.get("priority", "")
                    priority_str = f" [{priority}]" if priority else ""
                    story.append(Paragraph(f"• {text}{priority_str}", bullet_style))
            else:
                story.append(Paragraph("• No requirements extracted for this category.", bullet_style))
            story.append(Spacer(1, 4))
    else:
        story.append(Paragraph("No requirements available.", body_style))

    # Assumptions
    if output.assumptions:
        story.append(Paragraph("Assumptions", h1_style))
        if isinstance(output.assumptions, list):
            for item in output.assumptions:
                text = item if isinstance(item, str) else item.get("text", "")
                story.append(Paragraph(f"• {text}", bullet_style))
        else:
            story.append(Paragraph(str(output.assumptions), body_style))

    # Open Questions
    if output.open_questions:
        story.append(Paragraph("Open Questions", h1_style))
        if isinstance(output.open_questions, list):
            for item in output.open_questions:
                text = item if isinstance(item, str) else item.get("text", "")
                story.append(Paragraph(f"• {text}", bullet_style))
        else:
            story.append(Paragraph(str(output.open_questions), body_style))

    story.append(Spacer(1, 15))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#d1d5db"), spaceBefore=10, spaceAfter=8))
    story.append(Paragraph("Generated by DocPPT Intelligence Tool", footer_style))

    # Build PDF
    doc_template.build(story)

    # Log to files table if not already exists
    existing_file = db.query(File).filter(
        File.session_id == session_uuid,
        File.file_role == "output",
        File.file_type == "pdf"
    ).first()

    if not existing_file:
        db_file = File(
            session_id=session_uuid,
            user_id=session.user_id,
            file_role="output",
            file_type="pdf",
            storage_path=filepath,
            original_filename=f"{session.input_label or 'document'}_analysis.pdf",
            mime_type="application/pdf",
            size_bytes=os.path.getsize(filepath)
        )
        db.add(db_file)
        db.commit()

    return FileResponse(
        filepath,
        filename=f"{session.input_label or 'document'}_analysis.pdf",
        media_type="application/pdf"
    )
